/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package automotiverentalsystem;

/**
 *
 * @author marlo
 */
public class carMenu extends javax.swing.JFrame {

    /**
     * Creates new form carMenu
     */
    public carMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sportscarBtn = new javax.swing.JLabel();
        vanBtn = new javax.swing.JLabel();
        pickupBtn = new javax.swing.JLabel();
        carsBtn = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 204, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sportscarBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        sportscarBtn.setForeground(new java.awt.Color(255, 255, 255));
        sportscarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sportscarBtn.setText("SPORTS CAR");
        sportscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sportscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sportscarBtnMouseClicked(evt);
            }
        });
        jPanel1.add(sportscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 270, 60));

        vanBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        vanBtn.setForeground(new java.awt.Color(255, 255, 255));
        vanBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vanBtn.setText("VAN");
        vanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vanBtnMouseClicked(evt);
            }
        });
        jPanel1.add(vanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 270, 60));

        pickupBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        pickupBtn.setForeground(new java.awt.Color(255, 255, 255));
        pickupBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pickupBtn.setText("PICKUP TRUCK");
        pickupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pickupBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pickupBtnMouseClicked(evt);
            }
        });
        jPanel1.add(pickupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 260, 60));

        carsBtn.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        carsBtn.setForeground(new java.awt.Color(255, 255, 255));
        carsBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carsBtn.setText("CAR/SEDAN/COMPACT");
        carsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carsBtnMouseClicked(evt);
            }
        });
        jPanel1.add(carsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 270, 60));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (67).png")); // NOI18N
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAR MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 30, 430, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (12).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 270, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (10).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 270, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (9).png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 270, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (11).png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 270, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        dispose ();

    }//GEN-LAST:event_jLabel25MouseClicked

    private void sportscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sportscarBtnMouseClicked
        // TODO add your handling code here:
        
        sportscarChoices nJframe = new sportscarChoices ();
        dispose();
        nJframe.show();
        
    }//GEN-LAST:event_sportscarBtnMouseClicked

    private void carsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsBtnMouseClicked
        // TODO add your handling code here:
        
        carChoices nJframe = new carChoices ();
        dispose();
        nJframe.show();
        
    }//GEN-LAST:event_carsBtnMouseClicked

    private void pickupBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pickupBtnMouseClicked
        // TODO add your handling code here:
        
        pickupChoices nJframe = new pickupChoices ();
        dispose();
        nJframe.show();
        
    }//GEN-LAST:event_pickupBtnMouseClicked

    private void vanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vanBtnMouseClicked
        // TODO add your handling code here:
        
        vanChoices nJframe = new vanChoices ();
        dispose();
        nJframe.show();
        
    }//GEN-LAST:event_vanBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pickupBtn;
    private javax.swing.JLabel sportscarBtn;
    private javax.swing.JLabel vanBtn;
    // End of variables declaration//GEN-END:variables
}
