/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package automotiverentalsystem;

import static automotiverentalsystem.systemDashboard.Instance;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author marlo
 */
public class customerservicePane extends javax.swing.JInternalFrame {

  
    
    public customerservicePane() {
        initComponents();
        
        
        
        
           
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chatMenuColor = new javax.swing.JPanel();
        menuChat = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        chatName1 = new javax.swing.JLabel();
        chatName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        msg_button = new javax.swing.JButton();
        chatHeadColor = new javax.swing.JPanel();
        chatHead = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (74).png")); // NOI18N
        jLabel7.setText("  ORDERS");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 210, 90));

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (75).png")); // NOI18N
        jLabel8.setText("  CHECKOUT");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 210, 90));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (77).png")); // NOI18N
        jLabel10.setText("  FEEDBACK");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 210, 90));

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (76).png")); // NOI18N
        jLabel9.setText("  TEAM");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, 90));

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 15, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (6).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (5).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (4).png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (3).png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("SUPPORT REQUEST");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        chatMenuColor.setBackground(new java.awt.Color(255, 204, 204));
        chatMenuColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuChat.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        menuChat.setForeground(new java.awt.Color(255, 255, 255));
        menuChat.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (74).png")); // NOI18N
        menuChat.setText("ORDERS");
        chatMenuColor.add(menuChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -6, -1, 70));

        jPanel1.add(chatMenuColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 350, 60));

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatName1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        chatName1.setForeground(new java.awt.Color(0, 255, 51));
        chatName1.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (82).png")); // NOI18N
        chatName1.setText("    ORDER 2");
        chatName1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chatName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatName1MouseClicked(evt);
            }
        });
        jPanel4.add(chatName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 250, 60));

        chatName.setBackground(new java.awt.Color(0, 255, 51));
        chatName.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        chatName.setForeground(new java.awt.Color(0, 255, 51));
        chatName.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (81).png")); // NOI18N
        chatName.setText("    ORDER 1");
        chatName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chatName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatNameMouseClicked(evt);
            }
        });
        jPanel4.add(chatName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 250, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (7).png")); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 290, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\image (7).png")); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 290, 60));

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MESSAGE REQUEST");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 350, 370));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 360));

        msg_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_textActionPerformed(evt);
            }
        });
        jPanel3.add(msg_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 220, 50));

        msg_button.setBackground(new java.awt.Color(153, 204, 255));
        msg_button.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        msg_button.setForeground(new java.awt.Color(255, 255, 255));
        msg_button.setText("E N T E R");
        msg_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(msg_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 90, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 340, 440));

        chatHeadColor.setBackground(new java.awt.Color(255, 204, 204));
        chatHeadColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatHead.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        chatHead.setForeground(new java.awt.Color(255, 255, 255));
        chatHead.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (81).png")); // NOI18N
        chatHead.setText("CUSTOMER 1");
        chatHeadColor.add(chatHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 2, 140, 40));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (83).png")); // NOI18N
        jLabel11.setText("ONLINE");
        chatHeadColor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 80, 40));

        jPanel1.add(chatHeadColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 340, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        
        menuChat.setText("ORDERS");
        menuChat.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (74).png"));
        chatMenuColor.setBackground(new java.awt.Color(255, 204, 204));
        chatHeadColor.setBackground(new java.awt.Color(255, 204, 204));
        chatName.setText("   ORDER 1");
        chatName1.setText("   ORDER 2");
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void chatNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatNameMouseClicked
        // TODO add your handling code here:
        
        chatHead.setText(" CUSTOMER 1");
        chatHead.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (81).png"));
        
    }//GEN-LAST:event_chatNameMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        
        menuChat.setText("CHECKOUT");
        menuChat.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (75).png"));
        chatMenuColor.setBackground(new java.awt.Color (255, 51, 51));
        chatHeadColor.setBackground(new java.awt.Color (255, 51, 51));
        chatName.setText("   CHECKOUT 1");
        chatName1.setText("   CHECKOUT 2");
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        
        menuChat.setText("TEAM");
        menuChat.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (76).png"));
        chatMenuColor.setBackground(new java.awt.Color(0,153,204));
        chatHeadColor.setBackground(new java.awt.Color(0,153,204));
        chatName.setText("   TEAM 1");
        chatName1.setText("   TEAM 2");
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        
         menuChat.setText("FEEDBACK");
         menuChat.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (77).png"));
        chatMenuColor.setBackground(new java.awt.Color(0,204,102));
        chatHeadColor.setBackground(new java.awt.Color(0,204,102));
        chatName.setText("   FEEDBACK 1");
        chatName1.setText("   FEEDBACK 2");
        jLabel11.setForeground(new java.awt.Color(242,242,242));
        
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void chatName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatName1MouseClicked
        // TODO add your handling code here:
        
        chatHead.setText(" CUSTOMER 2");
        chatHead.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (82).png"));
        
    }//GEN-LAST:event_chatName1MouseClicked

    private void msg_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msg_textActionPerformed

    private void msg_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_buttonActionPerformed
        // TODO add your handling code here:
        String Text1 = msg_text.getText();
        msg_area.setText("Service: "+Text1);
        
    }//GEN-LAST:event_msg_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chatHead;
    private javax.swing.JPanel chatHeadColor;
    private javax.swing.JPanel chatMenuColor;
    private javax.swing.JLabel chatName;
    private javax.swing.JLabel chatName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menuChat;
    private javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_button;
    private javax.swing.JTextField msg_text;
    // End of variables declaration//GEN-END:variables
}
