/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package automotiverentalsystem;

import automotiverentalsystem.booknowBtn.aventador;
import automotiverentalsystem.booknowBtn.bugatti;
import automotiverentalsystem.booknowBtn.gtr;
import automotiverentalsystem.booknowBtn.porsche;
import javax.swing.JLabel;

/**
 *
 * @author marlo
 */
public class sportscarChoices extends javax.swing.JFrame {

   
    public static sportscarChoices Instance;
    public JLabel lbl;
    public JLabel lbl1;
    public JLabel lbl2;
    public JLabel lbl3;
    
    
    public sportscarChoices() {
        initComponents();
        
        Instance = this;
        lbl = bugatti;
        lbl1 = aventador;
        lbl2 = gtr;
        lbl3 = porsche;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        bugatti = new javax.swing.JLabel();
        aventador = new javax.swing.JLabel();
        gtr = new javax.swing.JLabel();
        porsche = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 204, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("SPORTS CAR");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 204, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (36).jpg")); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 160));

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (86).png")); // NOI18N
        jLabel11.setText("4.7");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PORSCHE 911");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel25.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (89).png")); // NOI18N
        jLabel25.setText("   AUTOMATIC");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, 20));

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (88).png")); // NOI18N
        jLabel22.setText("   PREMIUM GAS");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, 20));

        jLabel31.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (87).png")); // NOI18N
        jLabel31.setText("   2 SEATS");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, 20));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 380, 180));

        jPanel8.setBackground(new java.awt.Color(0, 204, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (35).jpg")); // NOI18N
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 160));

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (86).png")); // NOI18N
        jLabel13.setText("4.9");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NISSAN GTR");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel34.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (89).png")); // NOI18N
        jLabel34.setText("   AUTOMATIC");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, 20));

        jLabel37.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (88).png")); // NOI18N
        jLabel37.setText("   PREMIUM GAS");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 20));

        jLabel40.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (87).png")); // NOI18N
        jLabel40.setText("   2 SEATS");
        jPanel8.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, 20));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 380, 180));

        jPanel9.setBackground(new java.awt.Color(0, 204, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (34).jpg")); // NOI18N
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 160));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (86).png")); // NOI18N
        jLabel12.setText("4.8");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LAMBORGHINI AVENTADOR");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel33.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (89).png")); // NOI18N
        jLabel33.setText("   AUTOMATIC");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, 20));

        jLabel36.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (88).png")); // NOI18N
        jLabel36.setText("   PREMIUM GAS");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, 20));

        jLabel39.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (87).png")); // NOI18N
        jLabel39.setText("   2 SEATS");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, 20));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 380, 180));

        jPanel10.setBackground(new java.awt.Color(0, 204, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (37).jpg")); // NOI18N
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 160));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (86).png")); // NOI18N
        jLabel14.setText("4.8");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BUGATTI VEYRON");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel35.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (89).png")); // NOI18N
        jLabel35.setText("   AUTOMATIC");
        jPanel10.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 130, 20));

        jLabel38.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (88).png")); // NOI18N
        jLabel38.setText("   PREMIUM GAS");
        jPanel10.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 20));

        jLabel41.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (87).png")); // NOI18N
        jLabel41.setText("   2 SEATS");
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, 20));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 380, 180));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BOOK NOW!");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 140, 30));

        jButton2.setBackground(new java.awt.Color(0, 255, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BOOK NOW!");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, 30));

        jButton3.setBackground(new java.awt.Color(0, 255, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BOOK NOW!");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 140, 30));

        jButton4.setBackground(new java.awt.Color(0, 255, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BOOK NOW!");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 140, 30));

        bugatti.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        bugatti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bugatti.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\icons8-green-circle-48.png")); // NOI18N
        bugatti.setText("AVAILABLE");
        jPanel3.add(bugatti, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 240, 50));

        aventador.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        aventador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aventador.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\icons8-green-circle-48.png")); // NOI18N
        aventador.setText("AVAILABLE");
        jPanel3.add(aventador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 50));

        gtr.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        gtr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gtr.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\icons8-green-circle-48.png")); // NOI18N
        gtr.setText("AVAILABLE");
        jPanel3.add(gtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 240, 50));

        porsche.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        porsche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        porsche.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\icons8-green-circle-48.png")); // NOI18N
        porsche.setText("AVAILABLE");
        jPanel3.add(porsche, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 240, 50));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\marlo\\Downloads\\Webp.net-resizeimage (67).png")); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:

        carMenu nJframe = new carMenu();
        nJframe.show();
        dispose ();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        aventador nJframe = new aventador ();
        nJframe.show();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        gtr nJframe = new gtr ();
        nJframe.show();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        porsche nJframe = new porsche ();
        nJframe.show();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        bugatti nJframe = new bugatti ();
        nJframe.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sportscarChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sportscarChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sportscarChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sportscarChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sportscarChoices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aventador;
    private javax.swing.JLabel bugatti;
    private javax.swing.JLabel gtr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel porsche;
    // End of variables declaration//GEN-END:variables
}
